version: '3.5'

services:
  app:
    build: .
    restart: always
    container_name: pweb-py
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "18000:8000"
    networks:
      - fromphpcompose
networks:
  fromphpcompose:
    name: php_default
    external: true