version: "3.9"

services:
  nginx:
    build:
      context: ./nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/static-content:/var/www/html:ro
    ports:
      - "6980:80"
  app:
    depends_on:
      - nginx
    build: .
    restart: always
    container_name: pweb-php
    volumes:
      - ./web:/app:ro
    #Nao publique porta