version: '3.5'

services:
  db:
    image: phdcoder/postgresbr
    restart: always
    volumes:
      - base_cliente:/var/lib/postgresql/data/pgdata
      - ./initdb:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: app
      POSTGRES_DB: site
      POSTGRES_PASSWORD: app2022
      PGDATA: /var/lib/postgresql/data/pgdata
      LANG: pt_BR.utf8
    ports:
      - "5999:5432"
  app:
    image: dmstr/php-yii2:latest-nginx
    restart: always
    container_name: pweb-php
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "7880:80"
volumes:
  base_cliente:
    external: true